-- MySQL Script generated by MySQL Workbench
-- Sun Nov 12 15:05:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aux_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aux_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aux_endereco` (
  `idaux_endereco` INT NOT NULL,
  `cep` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idaux_endereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `telefone` CHAR(9) NULL,
  `cpf` CHAR(11) NULL,
  `tipo_perfil` ENUM('cliente', 'funcionario', 'admin') NULL,
  `aux_endereco_idaux_endereco` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `aux_endereco_idaux_endereco`),
  INDEX `fk_usuario_aux_endereco1_idx` (`aux_endereco_idaux_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_aux_endereco1`
    FOREIGN KEY (`aux_endereco_idaux_endereco`)
    REFERENCES `mydb`.`aux_endereco` (`idaux_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`perfil` ;

CREATE TABLE IF NOT EXISTS `mydb`.`perfil` (
  `idperfil` INT NOT NULL,
  `tipo_perfil` VARCHAR(45) NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `idproduto` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `categoria` VARCHAR(45) NULL,
  `preco` DOUBLE(5,2) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `idpedido` INT NOT NULL,
  `data` DATE NULL,
  `valorTotal` VARCHAR(45) NULL,
  `usuario_idusuario` INT NOT NULL,
  `usuario_idusuario1` INT NOT NULL,
  `usuario_aux_endereco_idaux_endereco` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `usuario_idusuario`),
  INDEX `fk_pedidos_usuario1_idx` (`usuario_idusuario1` ASC, `usuario_aux_endereco_idaux_endereco` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_usuario1`
    FOREIGN KEY (`usuario_idusuario1` , `usuario_aux_endereco_idaux_endereco`)
    REFERENCES `mydb`.`usuario` (`idusuario` , `aux_endereco_idaux_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itenspedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`itenspedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`itenspedidos` (
  `pedidos_idpedido` INT NOT NULL,
  `pedidos_usuario_idusuario` INT NOT NULL,
  `produtos_idproduto` INT NOT NULL,
  PRIMARY KEY (`pedidos_idpedido`, `pedidos_usuario_idusuario`, `produtos_idproduto`),
  INDEX `fk_pedidos_has_produtos_produtos1_idx` (`produtos_idproduto` ASC) VISIBLE,
  INDEX `fk_pedidos_has_produtos_pedidos1_idx` (`pedidos_idpedido` ASC, `pedidos_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_produtos_pedidos1`
    FOREIGN KEY (`pedidos_idpedido` , `pedidos_usuario_idusuario`)
    REFERENCES `mydb`.`pedidos` (`idpedido` , `usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_produtos_produtos1`
    FOREIGN KEY (`produtos_idproduto`)
    REFERENCES `mydb`.`produtos` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
