-- MySQL Script generated by MySQL Workbench
-- Thu Dec  7 20:52:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_produtos` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_produtos` DEFAULT CHARACTER SET utf8 ;
USE `db_produtos` ;


-- -----------------------------------------------------
-- Table `produtos`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_produtos`.`produtos` ;

CREATE TABLE IF NOT EXISTS `db_produtos`.`produtos` (
  `idproduto` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `dataValiidade` VARCHAR(45) NULL,
  `preco` DOUBLE(5,2) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
